language: go
go:
  - "1.11"
script:
- travis_wait 45 make deploy
branches:
  only:
  - master
before_install:
#- npm install
- export PATH=./node_modules/.bin:$PATH
#- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- sudo apt-get install -y uidmap libseccomp-dev
- sudo curl -fSL "https://github.com/genuinetools/img/releases/download/v0.5.1/img-linux-amd64" -o "/usr/local/bin/img"
- sudo chmod a+x "/usr/local/bin/img"
- wget https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.tar.xz
- tar xf runc.tar.xz
- cd runc-1.0.0-rc5
- make
- sudo make install
