language: go
go:
  - "1.11"
sudo: required
services:
  - docker
script:
- travis_wait 45 make deploy
branches:
  only:
  - master
before_install:
- npm install
- export PATH=./node_modules/.bin:$PATH
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- pip install --user awscli
- eval $(aws ecr get-login --no-include-email)