[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.6.x"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.x"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.x"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.x"

[[constraint]]
  name = "github.com/eduncan911/podcast"
  version = "1.3.x"